return {
	title = "Ayu Dark",
	description = "A refined dark theme with bright accents, focusing on high contrast and elegant simplicity.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${red}" },
		["@variable.parameter"] = { fg = "${white}" },
		["@variable.member"] = { fg = "${fg}" },
		["@property"] = { fg = "${highlight}" },
		["@field"] = { fg = "${highlight}" },
		["@method"] = { fg = "${yellow}" },
		["@method.call"] = { fg = "${yellow}" },
		["@constant"] = { fg = "${orange}" },
		["@constant.builtin"] = { fg = "${orange}", bold = true },
		["@constant.macro"] = { fg = "${purple}" },
		["@type"] = { fg = "${purple}" },
		["@type.builtin"] = { fg = "${purple}" },
		["@type.definition"] = { fg = "${purple}" },
		["@function"] = { fg = "${yellow}", bold = true },
		["@function.builtin"] = { fg = "${cyan}" },
	},
	lightMode = {
		bg = "#fafafa",
		fg = "#5c6773",
		red = "#f07178",
		orange = "#ff8f40",
		yellow = "#ffb454",
		green = "#86b300",
		cyan = "#4dbf99",
		blue = "#399ee6",
		dark_blue = "#e0e7ee",
		purple = "#a37acc",
		white = "#828c99",
		black = "#f0f0f0",
		gray = "#abb0b6",
		dark_gray = "#f0f0f0",
		highlight = "#ffcc66",
		cursor_line = "#f2f2f2",
		comment = "#abb0b6",
		none = "NONE",
	},
	darkMode = {
		bg = "#0f1419",
		fg = "#e6e1cf",
		red = "#f07178",
		orange = "#ff8f40",
		yellow = "#ffb454",
		green = "#b8cc52",
		cyan = "#95e6cb",
		blue = "#59c2ff",
		dark_blue = "#151a1e",
		purple = "#d2a6ff",
		white = "#b3b1ad",
		black = "#0a0e14",
		gray = "#3e4b59",
		dark_gray = "#14191f",
		highlight = "#ffcc66",
		cursor_line = "#14191f",
		comment = "#5c6773",
		none = "NONE",
	},
}
