return {
	title = "Banana",
	description = "Polished obsidian and ripened yellow, consistent across light and dark.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${orange}", italic = true },
		["@variable.parameter"] = { fg = "${white}", italic = true },
		["@variable.member"] = { fg = "${cyan}" },
		["@property"] = { fg = "${cyan}" },
		["@field"] = { fg = "${cyan}" },
		["@function"] = { fg = "${blue}", bold = true },
		["@function.builtin"] = { fg = "${yellow}" },
		["@method"] = { fg = "${blue}" },
		["@method.call"] = { fg = "${blue}" },
		["@keyword"] = { fg = "${yellow}", bold = true },
		["@keyword.function"] = { fg = "${yellow}", bold = true },
		["@keyword.return"] = { fg = "${highlight}", bold = true },
		["@operator"] = { fg = "${white}" },
		["@punctuation"] = { fg = "${white}" },
		["@type"] = { fg = "${purple}", italic = true },
		["@type.builtin"] = { fg = "${purple}" },
		["@constant"] = { fg = "${orange}" },
		["@constant.builtin"] = { fg = "${orange}", bold = true },
		["@string"] = { fg = "${green}" },
		["@number"] = { fg = "${orange}" },
		["@boolean"] = { fg = "${orange}" },
		["@comment"] = { fg = "${comment}", italic = true },
	},
	lightMode = {
		bg = "#fff9e6",
		fg = "#121212",
		red = "#ff5c5c",
		orange = "#e67e22",
		yellow = "#b8860b",
		green = "#4d6600",
		cyan = "#daa520",
		blue = "#8b6508",
		dark_blue = "#f2ead3",
		purple = "#7d6b2c",
		white = "#5c5747",
		black = "#f2ead3",
		gray = "#a6a085",
		dark_gray = "#f2ead3",
		highlight = "#ffd700",
		cursor_line = "#f2ead3",
		comment = "#a6a085",
		none = "NONE",
	},
	darkMode = {
		bg = "#0d0d0d",
		fg = "#e6e6e6",
		red = "#ff5c5c",
		orange = "#ffb347",
		yellow = "#ffe066",
		green = "#c3e88d",
		cyan = "#ffd700",
		blue = "#ffcc00",
		dark_blue = "#2a2a2a",
		purple = "#d4af37",
		white = "#a0a0a0",
		black = "#050505",
		gray = "#333333",
		dark_gray = "#1a1a1a",
		highlight = "#ffff00",
		cursor_line = "#1a1a1a",
		comment = "#666666",
		none = "NONE",
	},
}
