return {
	title = "Catppuccin",
	description = "Soothing pastel theme for the high-spirited! A modern classic for Neovim.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${red}" },
		["@variable.parameter"] = { fg = "${orange}", italic = true },
		["@variable.member"] = { fg = "${blue}" },
		["@property"] = { fg = "${blue}" },
		["@field"] = { fg = "${blue}" },
		["@function"] = { fg = "${blue}" },
		["@function.builtin"] = { fg = "${cyan}" },
		["@method"] = { fg = "${blue}" },
		["@method.call"] = { fg = "${blue}" },
		["@keyword"] = { fg = "${purple}" },
		["@keyword.function"] = { fg = "${purple}" },
		["@keyword.return"] = { fg = "${purple}" },
		["@operator"] = { fg = "${highlight}" },
		["@punctuation"] = { fg = "${white}" },
		["@constant"] = { fg = "${orange}" },
		["@constant.builtin"] = { fg = "${orange}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${yellow}" },
		["@string"] = { fg = "${green}" },
		["@number"] = { fg = "${orange}" },
		["@boolean"] = { fg = "${orange}" },
		["@comment"] = { fg = "${comment}", italic = true },
		["@tag"] = { fg = "${purple}" },
		["@tag.attribute"] = { fg = "${yellow}", italic = true },
		["@label"] = { fg = "${blue}" },
	},
	lightMode = {
		bg = "#eff1f5",
		fg = "#4c4f69",
		red = "#d20f39",
		orange = "#fe640b",
		yellow = "#df8e1d",
		green = "#40a02b",
		cyan = "#179287",
		blue = "#1e66f5",
		dark_blue = "#bcc0cc",
		purple = "#8839ef",
		white = "#7c7f93",
		black = "#e6e9ef",
		gray = "#9ca0b0",
		dark_gray = "#e6e9ef",
		highlight = "#ea76cb",
		cursor_line = "#ccd0da",
		comment = "#9ca0b0",
		none = "NONE",
	},
	darkMode = {
		bg = "#1e1e2e",
		fg = "#cdd6f4",
		red = "#f38ba8",
		orange = "#fab387",
		yellow = "#f9e2af",
		green = "#a6e3a1",
		cyan = "#94e2d5",
		blue = "#89b4fa",
		dark_blue = "#45475a",
		purple = "#cba6f7",
		white = "#bac2de",
		black = "#11111b",
		gray = "#585b70",
		dark_gray = "#181825",
		highlight = "#f5c2e7",
		cursor_line = "#313244",
		comment = "#7f849c",
		none = "NONE",
	},
}
