return {
	title = "Deep Sea",
	description = "A deep oceanic palette using slate navy foundations and vibrant cerulean accents.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${cyan}" },
		["@variable.parameter"] = { fg = "${white}", italic = true },
		["@variable.member"] = { fg = "${cyan}" },
		["@property"] = { fg = "${cyan}" },
		["@field"] = { fg = "${cyan}" },
		["@function"] = { fg = "${blue}", bold = true },
		["@function.builtin"] = { fg = "${cyan}" },
		["@method"] = { fg = "${blue}" },
		["@method.call"] = { fg = "${blue}", italic = true },
		["@keyword"] = { fg = "${purple}", bold = true },
		["@keyword.return"] = { fg = "${highlight}", bold = true },
		["@operator"] = { fg = "${blue}" },
		["@punctuation"] = { fg = "${white}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${yellow}", italic = true },
		["@constant"] = { fg = "${orange}" },
		["@string"] = { fg = "${green}" },
		["@number"] = { fg = "${orange}" },
		["@boolean"] = { fg = "${orange}" },
		["@comment"] = { fg = "${comment}", italic = true },
	},
	lightMode = {
		bg = "#f0f4f8",
		fg = "#243b53",
		red = "#af2a2a",
		orange = "#9e4a00",
		yellow = "#835c00",
		green = "#2a5f2a",
		cyan = "#006b7d",
		blue = "#104eb2",
		dark_blue = "#d9e2ec",
		purple = "#513c83",
		white = "#627d98",
		black = "#bcccdc",
		gray = "#829ab1",
		dark_gray = "#d9e2ec",
		highlight = "#007ace",
		cursor_line = "#e1e8f0",
		comment = "#97a3b6",
		none = "NONE",
	},
	darkMode = {
		bg = "#101622",
		fg = "#d9e2ec",
		red = "#ff6b6b",
		orange = "#ff9f43",
		yellow = "#f1c40f",
		green = "#55efc4",
		cyan = "#00d2ff",
		blue = "#00a8ff",
		dark_blue = "#1a2a3a",
		purple = "#a29bfe",
		white = "#9fb3c8",
		black = "#0b0f19",
		gray = "#334e68",
		dark_gray = "#1a202c",
		highlight = "#48bb78",
		cursor_line = "#1d2735",
		comment = "#627d98",
		none = "NONE",
	},
}
