return {
	title = "Crimson Slate",
	description = "A professional dark theme with slate gray tones and deep crimson highlights.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${red}" },
		["@variable.parameter"] = { fg = "${white}", italic = true },
		["@variable.member"] = { fg = "${cyan}" },
		["@property"] = { fg = "${cyan}" },
		["@field"] = { fg = "${cyan}" },
		["@function"] = { fg = "${red}", bold = true },
		["@function.builtin"] = { fg = "${orange}" },
		["@method"] = { fg = "${red}" },
		["@method.call"] = { fg = "${red}" },
		["@keyword"] = { fg = "${purple}", bold = true },
		["@keyword.return"] = { fg = "${highlight}", bold = true },
		["@operator"] = { fg = "${white}" },
		["@punctuation"] = { fg = "${gray}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${yellow}", italic = true },
		["@constant"] = { fg = "${orange}" },
		["@string"] = { fg = "${green}" },
		["@number"] = { fg = "${orange}" },
		["@boolean"] = { fg = "${red}", bold = true },
		["@comment"] = { fg = "${comment}", italic = true },
	},
	lightMode = {
		bg = "#f2f2f2",
		fg = "#3d3535",
		red = "#b91c1c",
		orange = "#c2410c",
		yellow = "#854d0e",
		green = "#166534",
		cyan = "#991b1b",
		blue = "#1e40af",
		dark_blue = "#e5e5e5",
		purple = "#7f1d1d",
		white = "#57534e",
		black = "#d6d3d1",
		gray = "#a8a29e",
		dark_gray = "#e5e7eb",
		highlight = "#dc2626",
		cursor_line = "#f3f4f6",
		comment = "#78716c",
		none = "NONE",
	},
	darkMode = {
		bg = "#1a1a1a",
		fg = "#e5e5e5",
		red = "#ff4d4d",
		orange = "#ff944d",
		yellow = "#fbbf24",
		green = "#a3be8c",
		cyan = "#f87171",
		blue = "#81a1c1",
		dark_blue = "#262626",
		purple = "#f43f5e",
		white = "#a3a3a3",
		black = "#0f0f0f",
		gray = "#525252",
		dark_gray = "#262626",
		highlight = "#e11d48",
		cursor_line = "#2d2d2d",
		comment = "#737373",
		none = "NONE",
	},
}
