return {
	title = "Dracula",
	description = "The official Dracula theme. High contrast, dark and vibrant.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${purple}", italic = true },
		["@variable.parameter"] = { fg = "${orange}", italic = true },
		["@variable.member"] = { fg = "${fg}" },
		["@property"] = { fg = "${fg}" },
		["@field"] = { fg = "${fg}" },
		["@function"] = { fg = "${green}" },
		["@function.builtin"] = { fg = "${cyan}", italic = true },
		["@method"] = { fg = "${green}" },
		["@method.call"] = { fg = "${green}" },
		["@keyword"] = { fg = "${purple}", bold = true },
		["@keyword.function"] = { fg = "${cyan}", italic = true },
		["@keyword.return"] = { fg = "${purple}" },
		["@operator"] = { fg = "${purple}" },
		["@punctuation"] = { fg = "${fg}" },
		["@constant"] = { fg = "${purple}" },
		["@constant.builtin"] = { fg = "${purple}" },
		["@type"] = { fg = "${cyan}", italic = true },
		["@type.builtin"] = { fg = "${cyan}", italic = true },
		["@string"] = { fg = "${yellow}" },
		["@number"] = { fg = "${purple}" },
		["@boolean"] = { fg = "${purple}" },
		["@comment"] = { fg = "${comment}", italic = true },
		["@tag"] = { fg = "${purple}" },
		["@tag.attribute"] = { fg = "${green}", italic = true },
	},
	lightMode = {
		bg = "#f8f8f2",
		fg = "#282a36",
		red = "#e54b4b",
		orange = "#e1913f",
		yellow = "#939a24",
		green = "#209d3b",
		cyan = "#00839e",
		blue = "#7b58ab",
		dark_blue = "#d6d6d6",
		purple = "#c23f8d",
		white = "#6272a4",
		black = "#ecece4",
		gray = "#949494",
		dark_gray = "#ecece4",
		highlight = "#f1fa8c",
		cursor_line = "#ecece4",
		comment = "#6272a4",
		none = "NONE",
	},
	darkMode = {
		bg = "#282a36",
		fg = "#f8f8f2",
		red = "#ff5555",
		orange = "#ffb86c",
		yellow = "#f1fa8c",
		green = "#50fa7b",
		cyan = "#8be9fd",
		blue = "#bd93f9",
		dark_blue = "#44475a",
		purple = "#ff79c6",
		white = "#bfbfbf",
		black = "#191a21",
		gray = "#6272a4",
		dark_gray = "#21222c",
		highlight = "#f1fa8c",
		cursor_line = "#44475a",
		comment = "#6272a4",
		none = "NONE",
	},
}
