return {
	title = "Evergreen",
	description = "A sophisticated forest palette using tonal greens for clarity without eye strain.",
	syntax = {
		["@variable"] = { fg = "${white}" },
		["@variable.builtin"] = { fg = "${red}" },
		["@variable.parameter"] = { fg = "${white}", italic = true },
		["@variable.member"] = { fg = "${cyan}" },
		["@property"] = { fg = "${cyan}" },
		["@field"] = { fg = "${cyan}" },
		["@function"] = { fg = "${green}", bold = true },
		["@function.builtin"] = { fg = "${yellow}" },
		["@method"] = { fg = "${green}" },
		["@method.call"] = { fg = "${green}", italic = true },
		["@keyword"] = { fg = "${purple}", bold = true },
		["@keyword.return"] = { fg = "${highlight}", bold = true },
		["@operator"] = { fg = "${orange}" },
		["@punctuation"] = { fg = "${gray}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${yellow}", italic = true },
		["@constant"] = { fg = "${orange}" },
		["@string"] = { fg = "${orange}" },
		["@number"] = { fg = "${orange}" },
		["@boolean"] = { fg = "${red}" },
		["@comment"] = { fg = "${comment}", italic = true },
	},
	lightMode = {
		bg = "#f1f3f1",
		fg = "#2d3a2d",
		red = "#a03a3a",
		orange = "#955f26",
		yellow = "#7d6b2c",
		green = "#3e6b3e",
		cyan = "#2c7070",
		blue = "#3a5a7a",
		dark_blue = "#d8e2d8",
		purple = "#6e4a7d",
		white = "#4a5a4a",
		black = "#e0e6e0",
		gray = "#8a9a8a",
		dark_gray = "#e0e6e0",
		highlight = "#2c8a2c",
		cursor_line = "#e8ede8",
		comment = "#7a8a7a",
		none = "NONE",
	},
	darkMode = {
		bg = "#0f140f",
		fg = "#d1e0d1",
		red = "#ff6b6b",
		orange = "#ffb347",
		yellow = "#e2c08d",
		green = "#4ade80",
		cyan = "#81e6d9",
		blue = "#7aa2f7",
		dark_blue = "#1a241a",
		purple = "#c6a0f6",
		white = "#f0fff0",
		black = "#050805",
		gray = "#4a5a4a",
		dark_gray = "#161d16",
		highlight = "#00ff95",
		cursor_line = "#1a241a",
		comment = "#5c6d5c",
		none = "NONE",
	},
}
