return {
	title = "GitHub",
	description = "The classic GitHub look. Clean, familiar, and highly legible.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${purple}" },
		["@variable.parameter"] = { fg = "${orange}" },
		["@variable.member"] = { fg = "${fg}" },
		["@property"] = { fg = "${blue}" },
		["@field"] = { fg = "${blue}" },
		["@function"] = { fg = "${purple}", bold = true },
		["@function.builtin"] = { fg = "${purple}" },
		["@method"] = { fg = "${purple}" },
		["@method.call"] = { fg = "${purple}" },
		["@keyword"] = { fg = "${red}" },
		["@keyword.function"] = { fg = "${red}" },
		["@keyword.return"] = { fg = "${red}" },
		["@operator"] = { fg = "${blue}" },
		["@punctuation"] = { fg = "${fg}" },
		["@constant"] = { fg = "${blue}" },
		["@constant.builtin"] = { fg = "${blue}" },
		["@type"] = { fg = "${orange}", bold = true },
		["@type.builtin"] = { fg = "${orange}" },
		["@string"] = { fg = "${blue}" },
		["@string.escape"] = { fg = "${blue}", bold = true },
		["@number"] = { fg = "${blue}" },
		["@boolean"] = { fg = "${blue}" },
		["@comment"] = { fg = "${comment}", italic = true },
		["@tag"] = { fg = "${green}" },
		["@tag.attribute"] = { fg = "${blue}" },
		["@tag.delimiter"] = { fg = "${fg}" },
	},
	lightMode = {
		bg = "#ffffff",
		fg = "#24292f",
		red = "#cf222e",
		orange = "#953800",
		yellow = "#4d2d00",
		green = "#116329",
		cyan = "#0550ae",
		blue = "#0a3069",
		dark_blue = "#ddf4ff",
		purple = "#8250df",
		white = "#57606a",
		black = "#f6f8fa",
		gray = "#d0d7de",
		dark_gray = "#f6f8fa",
		highlight = "#fff8c5",
		cursor_line = "#f0f2f4",
		comment = "#6e7781",
		none = "NONE",
	},
	darkMode = {
		bg = "#0d1117",
		fg = "#c9d1d9",
		red = "#ff7b72",
		orange = "#ffa657",
		yellow = "#d29922",
		green = "#7ee787",
		cyan = "#a5d6ff",
		blue = "#79c0ff",
		dark_blue = "#1f6feb",
		purple = "#d2a8ff",
		white = "#8b949e",
		black = "#010409",
		gray = "#30363d",
		dark_gray = "#161b22",
		highlight = "#f2cc60",
		cursor_line = "#1c2128",
		comment = "#8b949e",
		none = "NONE",
	},
}
