return {
	title = "Gruvbox Material",
	description = "A warm, earthy palette with a retro-analog feel. Optimized for long coding sessions.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${red}" },
		["@variable.parameter"] = { fg = "${fg}" },
		["@variable.member"] = { fg = "${fg}" },
		["@property"] = { fg = "${cyan}" },
		["@field"] = { fg = "${cyan}" },
		["@method"] = { fg = "${green}" },
		["@method.call"] = { fg = "${green}" },
		["@constant"] = { fg = "${purple}" },
		["@constant.builtin"] = { fg = "${purple}", bold = true },
		["@constant.macro"] = { fg = "${purple}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${yellow}" },
		["@type.definition"] = { fg = "${yellow}" },
		["@function"] = { fg = "${green}", bold = true },
		["@function.builtin"] = { fg = "${orange}" },
	},
	lightMode = {
		bg = "#f2e5bc",
		fg = "#654735",
		red = "#af2528",
		orange = "#ba592c",
		yellow = "#b47109",
		green = "#73822d",
		cyan = "#4c7a5d",
		blue = "#45707a",
		dark_blue = "#ebdbb2",
		purple = "#945e80",
		white = "#7c6f64",
		black = "#fbf1c7",
		gray = "#a89984",
		dark_gray = "#ebdbb2",
		highlight = "#d8a657",
		cursor_line = "#ebdbb2",
		comment = "#a89984",
		none = "NONE",
	},
	darkMode = {
		bg = "#282828",
		fg = "#dfbf8e",
		red = "#ea6962",
		orange = "#e78a4e",
		yellow = "#d8a657",
		green = "#a9b665",
		cyan = "#89b482",
		blue = "#7daea3",
		dark_blue = "#3c3836",
		purple = "#d3869b",
		white = "#bd93f9",
		black = "#1d2021",
		gray = "#504945",
		dark_gray = "#32302f",
		highlight = "#e3a84e",
		cursor_line = "#32302f",
		comment = "#928374",
		none = "NONE",
	},
}
