return {
	title = "Monokai Pro",
	description = "The professional choice. High contrast, filter-machine aesthetic.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${red}" },
		["@variable.parameter"] = { fg = "${orange}" },
		["@variable.member"] = { fg = "${fg}" },
		["@property"] = { fg = "${cyan}" },
		["@field"] = { fg = "${cyan}" },
		["@method"] = { fg = "${green}" },
		["@method.call"] = { fg = "${green}" },
		["@constant"] = { fg = "${purple}" },
		["@constant.builtin"] = { fg = "${purple}", bold = true },
		["@constant.macro"] = { fg = "${purple}" },
		["@type"] = { fg = "${cyan}" },
		["@type.builtin"] = { fg = "${cyan}" },
		["@type.definition"] = { fg = "${cyan}" },
		["@function"] = { fg = "${green}", bold = true },
		["@function.builtin"] = { fg = "${cyan}" },
	},
	lightMode = {
		bg = "#fafafa",
		fg = "#2d2a2e",
		red = "#e91e63",
		orange = "#f97316",
		yellow = "#b48b00",
		green = "#689f38",
		cyan = "#0097a7",
		blue = "#673ab7",
		dark_blue = "#e0e0e0",
		purple = "#673ab7",
		white = "#939293",
		black = "#eeeeee",
		gray = "#939293",
		dark_gray = "#f1f1f1",
		highlight = "#ffd866",
		cursor_line = "#f1f1f1",
		comment = "#939293",
		none = "NONE",
	},
	darkMode = {
		bg = "#272a34",
		fg = "#fcfcfa",
		red = "#ff6188",
		orange = "#fc9867",
		yellow = "#ffd866",
		green = "#a9dc76",
		cyan = "#78dce8",
		blue = "#ab9df2",
		dark_blue = "#404455",
		purple = "#ab9df2",
		white = "#c1c0c0",
		black = "#191b21",
		gray = "#5b5f71",
		dark_gray = "#2d313d",
		highlight = "#ffd866",
		cursor_line = "#2d313d",
		comment = "#727072",
		none = "NONE",
	},
}
