return {
	title = "Night Owl",
	description = "A theme for the night owls out there. Deep blues and vibrant neons.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${red}" },
		["@variable.parameter"] = { fg = "${white}" },
		["@variable.member"] = { fg = "${cyan}" },
		["@property"] = { fg = "${cyan}" },
		["@field"] = { fg = "${cyan}" },
		["@method"] = { fg = "${blue}" },
		["@method.call"] = { fg = "${blue}" },
		["@constant"] = { fg = "${orange}" },
		["@constant.builtin"] = { fg = "${orange}", bold = true },
		["@constant.macro"] = { fg = "${purple}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${yellow}" },
		["@type.definition"] = { fg = "${yellow}" },
		["@function"] = { fg = "${blue}", bold = true },
		["@function.builtin"] = { fg = "${green}" },
	},
	lightMode = {
		bg = "#fbfbfb",
		fg = "#403f53",
		red = "#de3d3b",
		orange = "#f76d47",
		yellow = "#947131",
		green = "#487800",
		cyan = "#08916a",
		blue = "#288ed7",
		dark_blue = "#d9d9d9",
		purple = "#abb0f6",
		white = "#90a4ae",
		black = "#f0f0f0",
		gray = "#90a4ae",
		dark_gray = "#f0f0f0",
		highlight = "#2aa298",
		cursor_line = "#f0f0f0",
		comment = "#989fb1",
		none = "NONE",
	},
	darkMode = {
		bg = "#011627",
		fg = "#d6deeb",
		red = "#ef5350",
		orange = "#f78c6c",
		yellow = "#ecc48d",
		green = "#addb67",
		cyan = "#7fdbca",
		blue = "#82aaff",
		dark_blue = "#1d3b53",
		purple = "#c792ea",
		white = "#5f7e97",
		black = "#010e17",
		gray = "#4b6479",
		dark_gray = "#0b2942",
		highlight = "#21c7a8",
		cursor_line = "#0b2942",
		comment = "#637777",
		none = "NONE",
	},
}
