return {
	title = "Nordic",
	description = "An arctic, north-bluish color palette. Elegant, clean and focused.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${blue}" },
		["@variable.parameter"] = { fg = "${fg}", italic = true },
		["@variable.member"] = { fg = "${cyan}" },
		["@property"] = { fg = "${cyan}" },
		["@field"] = { fg = "${cyan}" },
		["@function"] = { fg = "${blue}" },
		["@function.builtin"] = { fg = "${cyan}" },
		["@method"] = { fg = "${blue}" },
		["@method.call"] = { fg = "${blue}" },
		["@keyword"] = { fg = "${purple}" },
		["@keyword.function"] = { fg = "${purple}" },
		["@keyword.return"] = { fg = "${purple}" },
		["@operator"] = { fg = "${cyan}" },
		["@punctuation"] = { fg = "${fg}" },
		["@constant"] = { fg = "${purple}" },
		["@constant.builtin"] = { fg = "${purple}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${cyan}" },
		["@string"] = { fg = "${green}" },
		["@number"] = { fg = "${purple}" },
		["@boolean"] = { fg = "${purple}" },
		["@comment"] = { fg = "${comment}", italic = true },
		["@tag"] = { fg = "${blue}" },
		["@tag.attribute"] = { fg = "${cyan}" },
		["@label"] = { fg = "${cyan}" },
	},
	lightMode = {
		-- Nord Snow Storm (Light)
		bg = "#e5e9f0",
		fg = "#2e3440",
		red = "#bf616a",
		orange = "#d08770",
		yellow = "#ebcb8b",
		green = "#a3be8c",
		cyan = "#88c0d0",
		blue = "#5e81ac",
		dark_blue = "#81a1c1",
		purple = "#b48ead",
		white = "#eceff4",
		black = "#d8dee9",
		gray = "#4c566a",
		dark_gray = "#d8dee9",
		highlight = "#8fbcbb",
		cursor_line = "#d8dee9",
		comment = "#9ea7b8",
		none = "NONE",
	},
	darkMode = {
		bg = "#2e3440",
		fg = "#d8dee9",
		red = "#bf616a",
		orange = "#d08770",
		yellow = "#ebcb8b",
		green = "#a3be8c",
		cyan = "#88c0d0",
		blue = "#81a1c1",
		dark_blue = "#5e81ac",
		purple = "#b48ead",
		white = "#e5e9f0",
		black = "#242933",
		gray = "#4c566a",
		dark_gray = "#3b4252",
		highlight = "#8fbcbb",
		cursor_line = "#3b4252",
		comment = "#616e88",
		none = "NONE",
	},
}
