return {
	title = "OneDarkPro",
	description = "Atom's iconic One Dark theme, ported to Neovim with full tree-sitter support and multiple flavor variations.",
	syntax = {
		["@variable"] = { fg = "${red}" },
		["@variable.builtin"] = { fg = "${yellow}" },
		["@variable.parameter"] = { fg = "${red}" },
		["@variable.member"] = { fg = "${red}" },
		["@property"] = { fg = "${red}" },
		["@field"] = { fg = "${red}" },
		["@method"] = { fg = "${blue}" },
		["@method.call"] = { fg = "${blue}" },
		["@constant"] = { fg = "${orange}" },
		["@constant.builtin"] = { fg = "${orange}", bold = true },
		["@constant.macro"] = { fg = "${cyan}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${yellow}" },
		["@type.definition"] = { fg = "${yellow}" },
		["@function"] = { fg = "${blue}" },
		["@function.builtin"] = { fg = "${cyan}" },
	},
	lightMode = {
		bg = "#fafafa",
		fg = "#383a42",
		red = "#e45649",
		orange = "#986801",
		yellow = "#c18401",
		green = "#50a14f",
		cyan = "#0184bc",
		blue = "#4078f2",
		dark_blue = "#dbe6ff",
		purple = "#a626a4",
		white = "#a0a1a7",
		black = "#f0f0f1",
		gray = "#9fa0a6",
		dark_gray = "#eeeeee",
		highlight = "#e2be7d",
		cursor_line = "#f2f2f2",
		comment = "#a0a1a7",
		none = "NONE",
	},
	darkMode = {
		bg = "#0e1013",
		fg = "#abb2bf",
		red = "#e06c75",
		orange = "#d19a66",
		yellow = "#e5c07b",
		green = "#98c379",
		cyan = "#56b6c2",
		blue = "#61afef",
		dark_blue = "#3A7ACD",
		purple = "#c678dd",
		white = "#abb2bf",
		black = "#1e2227",
		gray = "#3e4452",
		dark_gray = "#282c34",
		highlight = "#e2be7d",
		cursor_line = "#31343d",
		comment = "#7f848e",
		none = "NONE",
	},
}
