return {
	title = "RetroWave",
	description = "A refined evolution of neon aesthetics, trading harsh contrasts for deep obsidian depths and industrial slate tones.",
	syntax = {
		["@variable"] = { fg = "${green}" },
		["@variable.builtin"] = { fg = "${red}", italic = true },
		["@variable.parameter"] = { fg = "${cyan}", italic = true },
		["@variable.member"] = { fg = "${yellow}" },
		["@property"] = { fg = "${yellow}" },
		["@field"] = { fg = "${yellow}" },
		["@function"] = { fg = "${blue}", bold = true },
		["@function.builtin"] = { fg = "${orange}" },
		["@method"] = { fg = "${blue}", bold = true },
		["@method.call"] = { fg = "${blue}" },
		["@keyword"] = { fg = "${purple}", bold = true },
		["@keyword.function"] = { fg = "${purple}", bold = true },
		["@keyword.return"] = { fg = "${highlight}", bold = true },
		["@operator"] = { fg = "${highlight}" },
		["@punctuation"] = { fg = "${white}" },
		["@type"] = { fg = "${orange}" },
		["@type.builtin"] = { fg = "${orange}", italic = true },
		["@constant"] = { fg = "${purple}" },
		["@constant.builtin"] = { fg = "${orange}", bold = true },
		["@constant.macro"] = { fg = "${highlight}" },
		["@string"] = { fg = "${green}" },
		["@string.escape"] = { fg = "${highlight}" },
		["@number"] = { fg = "${orange}" },
		["@boolean"] = { fg = "${highlight}" },
		["@comment"] = { fg = "${comment}", italic = true },
		["@label"] = { fg = "${highlight}" },
	},
	lightMode = {
		bg = "#e6e9ef",
		fg = "#282a36",
		red = "#ff2a6d",
		orange = "#f68d4d",
		yellow = "#dfa000",
		green = "#00a871",
		cyan = "#008fb3",
		blue = "#4d55ff",
		dark_blue = "#cbd2e0",
		purple = "#9d34d9",
		white = "#7b7bbd",
		black = "#bcc4d1",
		gray = "#8c92a3",
		dark_gray = "#d1d6e0",
		highlight = "#ff00ff",
		cursor_line = "#d8dee9",
		comment = "#7e8294",
		none = "NONE",
	},
	darkMode = {
		bg = "#070514",
		fg = "#e5e9f0",
		red = "#ff2a6d",
		orange = "#ff9e64",
		yellow = "#ffcc33",
		green = "#05ffa1",
		cyan = "#00d9ff",
		blue = "#6b70ff",
		dark_blue = "#12102e",
		purple = "#b24bf3",
		white = "#d1d1e0",
		black = "#030208",
		gray = "#323c58",
		dark_gray = "#0a091a",
		highlight = "#ff00ff",
		cursor_line = "#12102e",
		comment = "#636da6",
		none = "NONE",
	},
}
