return {
	title = "Rosé Pine",
	description = "All natural pine, low light. Soho vibes for the focused developer.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${red}" },
		["@variable.parameter"] = { fg = "${white}" },
		["@variable.member"] = { fg = "${cyan}" },
		["@property"] = { fg = "${cyan}" },
		["@field"] = { fg = "${cyan}" },
		["@method"] = { fg = "${blue}" },
		["@method.call"] = { fg = "${blue}" },
		["@constant"] = { fg = "${orange}" },
		["@constant.builtin"] = { fg = "${orange}", bold = true },
		["@constant.macro"] = { fg = "${purple}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${yellow}" },
		["@type.definition"] = { fg = "${yellow}" },
		["@function"] = { fg = "${green}", bold = true },
		["@function.builtin"] = { fg = "${blue}" },
	},
	lightMode = {
		bg = "#faf4ed",
		fg = "#575279",
		red = "#b4637a",
		orange = "#ea9d34",
		yellow = "#d7827e",
		green = "#286983",
		cyan = "#56949f",
		blue = "#907aa9",
		dark_blue = "#f2e9e1",
		purple = "#907aa9",
		white = "#797593",
		black = "#fffaf3",
		gray = "#9893a5",
		dark_gray = "#f2e9e1",
		highlight = "#d7827e",
		cursor_line = "#f4ede8",
		comment = "#9893a5",
		none = "NONE",
	},
	darkMode = {
		bg = "#191724",
		fg = "#e0def4",
		red = "#eb6f92",
		orange = "#f6c177",
		yellow = "#ebbcba",
		green = "#31748f",
		cyan = "#9ccfd8",
		blue = "#c4a7e7",
		dark_blue = "#2a283e",
		purple = "#c4a7e7",
		white = "#524f67",
		black = "#1f1d2e",
		gray = "#6e6a86",
		dark_gray = "#26233a",
		highlight = "#ebbcba",
		cursor_line = "#1f1d2e",
		comment = "#908caa",
		none = "NONE",
	},
}
