return {
	title = "Tokyo Night",
	description = "A clean theme that celebrates the lights of Downtown Tokyo at night.",
	syntax = {
		["@variable"] = { fg = "${fg}" },
		["@variable.builtin"] = { fg = "${red}" },
		["@variable.parameter"] = { fg = "${orange}", italic = true },
		["@variable.member"] = { fg = "${cyan}" },
		["@property"] = { fg = "${green}" },
		["@field"] = { fg = "${green}" },
		["@function"] = { fg = "${blue}" },
		["@function.builtin"] = { fg = "${cyan}" },
		["@method"] = { fg = "${blue}" },
		["@method.call"] = { fg = "${blue}" },
		["@keyword"] = { fg = "${purple}", italic = true },
		["@keyword.function"] = { fg = "${purple}" },
		["@keyword.return"] = { fg = "${purple}" },
		["@keyword.operator"] = { fg = "${purple}" },
		["@operator"] = { fg = "${cyan}" },
		["@punctuation"] = { fg = "${cyan}" },
		["@constant"] = { fg = "${orange}" },
		["@constant.builtin"] = { fg = "${orange}" },
		["@constant.macro"] = { fg = "${purple}" },
		["@type"] = { fg = "${yellow}" },
		["@type.builtin"] = { fg = "${blue}" },
		["@type.definition"] = { fg = "${yellow}" },
		["@string"] = { fg = "${green}" },
		["@string.escape"] = { fg = "${highlight}" },
		["@number"] = { fg = "${orange}" },
		["@boolean"] = { fg = "${orange}" },
		["@comment"] = { fg = "${comment}", italic = true },
		["@label"] = { fg = "${highlight}" },
		["@tag"] = { fg = "${red}" },
		["@tag.attribute"] = { fg = "${purple}" },
		["@tag.delimiter"] = { fg = "${cyan}" },
	},
	lightMode = {
		bg = "#e1e2e7",
		fg = "#3760bf",
		red = "#f52a65",
		orange = "#b15c00",
		yellow = "#8c6c3e",
		green = "#587539",
		cyan = "#007197",
		blue = "#2e7de9",
		dark_blue = "#b4b5b9",
		purple = "#9854f1",
		white = "#4d5b80",
		black = "#d0d5e3",
		gray = "#a8aecb",
		dark_gray = "#cfd2dd",
		highlight = "#9854f1",
		cursor_line = "#d0d5e3",
		comment = "#848cb5",
		none = "NONE",
	},
	darkMode = {
		bg = "#24283b",
		fg = "#c0caf5",
		red = "#f7768e",
		orange = "#ff9e64",
		yellow = "#e0af68",
		green = "#9ece6a",
		cyan = "#7dcfff",
		blue = "#7aa2f7",
		dark_blue = "#3d59a1",
		purple = "#bb9af7",
		white = "#a9b1d6",
		black = "#1d202f",
		gray = "#444b6a",
		dark_gray = "#292e42",
		highlight = "#bb9af7",
		cursor_line = "#2e344e",
		comment = "#565f89",
		none = "NONE",
	},
}
